"""
Configurable UART log parser — infrastructure layer.

Projects instantiate UartParser with their own event definitions (derived
from docs/toolchain_config.md [firmware.uart_format]) in src/analysis.py,
which is generated by `/toolchain scaffold`.

This module contains no domain knowledge. It does not know what a step,
a snapshot, a temperature reading, or any other physical event looks like.

Typical project usage (in scaffolded src/analysis.py):
    from crucible.signal.analysis import UartParser, EventDefinition

    PARSER = UartParser(
        event_definitions=[
            EventDefinition(
                name="primary_event",
                pattern=r"STEP\\s+#(\\d+)\\s+ts=(\\d+)\\s+metric=([\\d.]+)",
                fields=["index", "ts_ms", "value"],
                converters=[int, float, float],
            ),
        ],
        session_end_marker="SESSION_END",
    )
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Callable

from crucible.signal.events import UartEvent, SessionEndEvent


@dataclass
class EventDefinition:
    """Definition of one UART event type emitted by the project's firmware.

    Parameters
    ----------
    name : str
        Logical name for this event type (e.g. "primary_event", "snapshot").
    pattern : str
        Regex pattern. Capture groups map to ``fields`` in order.
    fields : list[str]
        Field names corresponding to capture groups.
    converters : list[callable]
        Type converters for each capture group (e.g. int, float, str).
    """
    name: str
    pattern: str
    fields: list[str]
    converters: list[Callable[[str], Any]]
    _re: re.Pattern = field(init=False, repr=False)

    def __post_init__(self) -> None:
        self._re = re.compile(self.pattern)

    def match(self, line: str) -> UartEvent | None:
        """Try to match ``line`` against this definition. Return UartEvent or None."""
        m = self._re.search(line)
        if not m:
            return None
        values = {
            name: conv(m.group(i + 1))
            for i, (name, conv) in enumerate(zip(self.fields, self.converters))
        }
        return UartEvent(event_type=self.name, fields=values)


class UartParser:
    """Parse UART log lines into typed event objects.

    Parameters
    ----------
    event_definitions : list[EventDefinition]
        One entry per event type the firmware emits (excluding SESSION_END).
    session_end_marker : str
        Substring whose presence in a line marks the end of a session.
        Default: ``"SESSION_END"`` — matches all Crucible firmware conventions.
    """

    def __init__(
        self,
        event_definitions: list[EventDefinition],
        session_end_marker: str = "SESSION_END",
    ) -> None:
        self._defs = event_definitions
        self._end_re = re.compile(re.escape(session_end_marker))

    def parse_line(self, line: str) -> UartEvent | SessionEndEvent | None:
        """Parse one UART log line. Returns a typed event or None."""
        line = line.strip()
        if self._end_re.search(line):
            return SessionEndEvent()
        for defn in self._defs:
            ev = defn.match(line)
            if ev is not None:
                return ev
        return None

    def parse_log(
        self,
        text: str,
    ) -> tuple[list[UartEvent], list[SessionEndEvent]]:
        """Parse a full UART log string.

        Returns
        -------
        (events, session_ends)
            ``events`` is the ordered list of all non-SESSION_END parsed lines.
            ``session_ends`` is typically a single-element list.
        """
        events: list[UartEvent] = []
        ends: list[SessionEndEvent] = []
        for line in text.splitlines():
            ev = self.parse_line(line)
            if isinstance(ev, SessionEndEvent):
                ends.append(ev)
            elif ev is not None:
                events.append(ev)
        return events, ends
