"""
Generic UART event containers for the Crucible infrastructure layer.

Projects define domain-specific event dataclasses in src/events.py,
generated by `/toolchain scaffold` from docs/device_context.md
Signal Inventory and docs/toolchain_config.md [firmware.uart_format].

This module provides only the types used by the infrastructure layer itself.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class UartEvent:
    """A single parsed UART event line.

    Fields are keyed by the project-defined field names from
    docs/toolchain_config.md [firmware.uart_format].
    """
    event_type: str
    fields: dict[str, Any] = field(default_factory=dict)


@dataclass
class SessionEndEvent:
    """Emitted once at the end of a recording session.

    All Crucible firmware must emit a SESSION_END marker (or the
    project-configured equivalent). The Renode bridge polls for this
    sentinel to know when a simulation run is complete.
    """
    pass
