"""
crucible.transport — BLE transport layer (infrastructure).

Quick imports:
    from crucible.transport.ble import BleConsole
    from crucible.transport.ble import NUS_SERVICE_UUID, NUS_TX_UUID, NUS_RX_UUID

Project-specific BLE GATT service UUIDs, PDU layouts, and data download
functions belong in src/transport.py (generated by /toolchain scaffold if
the project uses a custom GATT service beyond NUS UART streaming).
"""
