"""
BLE transport layer — Nordic UART Service (NUS) console receiver.

Provides a generic BLE UART console that connects to any device advertising
the Nordic UART Service and streams UART lines to a callback or stdout.

The NUS UUIDs are a Nordic Semiconductor standard and are not project-specific.
Project-specific BLE data service UUIDs and PDU layouts belong in src/transport.py,
generated by `/toolchain scaffold` if the project uses a custom GATT service.

Requires: pip install bleak
"""
from __future__ import annotations

import asyncio
import sys
from typing import Callable, Optional

# ─────────────────────────────────────────────────────────────────────────────
# Nordic UART Service (NUS) UUIDs — standard across all Nordic BLE devices
# ─────────────────────────────────────────────────────────────────────────────

NUS_SERVICE_UUID = "6E400001-B5A3-F393-E0A9-E50E24DCCA9E"
NUS_TX_UUID      = "6E400003-B5A3-F393-E0A9-E50E24DCCA9E"  # device → host
NUS_RX_UUID      = "6E400002-B5A3-F393-E0A9-E50E24DCCA9E"  # host → device


# ─────────────────────────────────────────────────────────────────────────────
# NUS console receiver
# ─────────────────────────────────────────────────────────────────────────────

class BleConsole:
    """Stream UART output from a device over the Nordic UART Service.

    Scans for a named device, subscribes to the NUS TX characteristic,
    and streams newline-delimited lines to a callback (default: stdout).

    Usage (standalone)::

        console = BleConsole(device_name="MyDevice")
        asyncio.run(console.run())

    Usage (with callback)::

        def on_line(line: str) -> None:
            print(f"[DEVICE] {line}")

        console = BleConsole(device_name="MyDevice", on_line=on_line)
        asyncio.run(console.run())
    """

    def __init__(
        self,
        device_name: str,
        scan_timeout: float = 15.0,
        on_line: Optional[Callable[[str], None]] = None,
    ) -> None:
        self.device_name  = device_name
        self.scan_timeout = scan_timeout
        self.on_line      = on_line or (
            lambda line: (sys.stdout.write(line + "\n"), sys.stdout.flush())
        )
        self._buf = ""

    def _handle_notify(self, _sender: object, data: bytearray) -> None:
        self._buf += data.decode("utf-8", errors="replace")
        while "\n" in self._buf:
            line, self._buf = self._buf.split("\n", 1)
            self.on_line(line)

    async def run(self) -> None:
        """Scan, connect, and stream until KeyboardInterrupt."""
        try:
            from bleak import BleakScanner, BleakClient
        except ImportError:
            print("bleak not installed. Install with: pip install bleak", file=sys.stderr)
            sys.exit(1)

        device = None
        while device is None:
            print(f"Scanning for '{self.device_name}*'...")
            device = await BleakScanner.find_device_by_name(
                self.device_name, timeout=self.scan_timeout
            )
            if device is None:
                print("Not found, retrying...")

        print(f"Found: {device.name} [{device.address}]")
        print("Connecting...")

        async with BleakClient(device) as client:
            print("Connected. Subscribing to NUS TX...")
            await client.start_notify(NUS_TX_UUID, self._handle_notify)
            print("--- device output ---")
            try:
                while True:
                    await asyncio.sleep(1)
            except KeyboardInterrupt:
                pass
            await client.stop_notify(NUS_TX_UUID)
            print("\n--- disconnected ---")
